# -*- coding: utf-8 -*-
"""Guardrail against Irrelevant Responses.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pN7Jy3jFvxb-ZWHFbZAGlMcLGS1Vf8n6
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def is_irrelevant(question, response, threshold=0.1):
    """
    Uses cosine similarity between question and response.
    Low similarity = likely irrelevant response.
    """
    vectorizer = TfidfVectorizer()
    vectors = vectorizer.fit_transform([question, response])
    score = cosine_similarity(vectors[0], vectors[1])[0][0]

    if score < threshold:
        return True, round(score, 4)
    return False, round(score, 4)


# Test pairs
pairs = [
    ("What is machine learning?",
     "Machine learning is a subset of AI that learns from data."),

    ("What is machine learning?",
     "I love eating pizza on weekends with extra cheese."),

    ("How does Python handle memory?",
     "Python uses automatic garbage collection to manage memory."),

    ("How does Python handle memory?",
     "The weather in Mumbai is hot and humid today."),
]

for question, response in pairs:
    irrelevant, score = is_irrelevant(question, response)
    status = "🚨 IRRELEVANT" if irrelevant else "✅ RELEVANT"
    print(f"{status} (similarity: {score})")
    print(f"  Q: {question}")
    print(f"  A: {response}\n")