# -*- coding: utf-8 -*-
"""Guardrail against Hallucinations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z1rJ0T4eXC2Y0s6u5OA5JVZ03B7jbO4k
"""

def check_hallucination(response, known_facts):
    """
    Checks if the response contradicts known facts.
    known_facts: dict of {keyword: expected_value}
    """
    hallucinations = []

    for keyword, correct_value in known_facts.items():
        if keyword.lower() in response.lower():
            if correct_value.lower() not in response.lower():
                hallucinations.append(
                    f"Possible hallucination: '{keyword}' mentioned but "
                    f"expected value '{correct_value}' not found in response."
                )

    if hallucinations:
        return True, hallucinations
    return False, ["Response aligns with known facts."]


# Known ground truth
known_facts = {
    "Eiffel Tower": "Paris",
    "Python": "1991",         # Python created in 1991
    "Einstein": "Theory of Relativity",
}

# Test responses
responses = [
    "The Eiffel Tower is located in Berlin and is a famous landmark.",  # Wrong city
    "Python was created in 1991 by Guido van Rossum.",                  # Correct
    "Einstein is known for his Theory of Relativity.",                  # Correct
    "The Eiffel Tower stands proudly in Paris, France.",                # Correct
]

for resp in responses:
    flagged, reasons = check_hallucination(resp, known_facts)
    status = "🚨 HALLUCINATION" if flagged else "✅ ACCURATE"
    print(f"{status} | Response: '{resp}'")
    for r in reasons:
        print(f"         → {r}")
    print()